-- AgriSense / Smart Agriculture Supabase setup
-- Project ref: vysijpetcmetbbtcipmp
--
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- It is safe to re-run: tables, indexes, bucket and policies are
-- created or refreshed without deleting application data.

begin;

-- ---------------------------------------------------------------------------
-- Shared timestamp trigger
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Module 1-3 snapshots
-- Keep raw values until the real sensors are calibrated.
-- ---------------------------------------------------------------------------

create table if not exists public.sensor_data (
  id bigint generated by default as identity primary key,
  device_id text not null default 'agrisense-prototype',

  soil_raw integer check (soil_raw is null or soil_raw between 0 and 4095),
  soil_percent numeric(5,2)
    check (soil_percent is null or soil_percent between 0 and 100),

  temperature_c numeric(5,2)
    check (temperature_c is null or temperature_c between -40 and 85),
  humidity_percent numeric(5,2)
    check (humidity_percent is null or humidity_percent between 0 and 100),
  light_raw integer check (light_raw is null or light_raw between 0 and 4095),
  light_lux numeric(10,2) check (light_lux is null or light_lux >= 0),

  water_raw integer check (water_raw is null or water_raw between 0 and 4095),
  water_level_percent numeric(5,2)
    check (water_level_percent is null or water_level_percent between 0 and 100),
  pump_runtime_seconds bigint
    check (pump_runtime_seconds is null or pump_runtime_seconds >= 0),
  estimated_water_litres numeric(12,3)
    check (estimated_water_litres is null or estimated_water_litres >= 0),

  pump_state text not null default 'UNKNOWN'
    check (pump_state in ('ON', 'OFF', 'UNKNOWN')),
  fan_state text not null default 'UNKNOWN'
    check (fan_state in ('ON', 'OFF', 'UNKNOWN')),
  led_state text not null default 'UNKNOWN'
    check (led_state in ('ON', 'OFF', 'UNKNOWN')),
  pump_mode text not null default 'AUTO'
    check (pump_mode in ('AUTO', 'MANUAL')),
  fan_mode text not null default 'AUTO'
    check (fan_mode in ('AUTO', 'MANUAL')),
  led_mode text not null default 'AUTO'
    check (led_mode in ('AUTO', 'MANUAL')),
  pump_lock boolean not null default false,

  wifi_rssi integer,
  data_quality text not null default 'VALID'
    check (data_quality in ('VALID', 'SUSPECT', 'INVALID')),
  metadata jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now()
);

-- Remove columns promised by the old weight/fertigation scope without deleting rows.
alter table public.sensor_data
  drop column if exists weight_raw,
  drop column if exists tank_weight_grams,
  drop column if exists nutrient_weight_grams;

-- Upgrade an existing prototype database without deleting historical rows.
alter table public.sensor_data
  add column if not exists pump_runtime_seconds bigint
    check (pump_runtime_seconds is null or pump_runtime_seconds >= 0),
  add column if not exists estimated_water_litres numeric(12,3)
    check (estimated_water_litres is null or estimated_water_litres >= 0);

create index if not exists sensor_data_recorded_at_idx
  on public.sensor_data (recorded_at desc);
create index if not exists sensor_data_device_time_idx
  on public.sensor_data (device_id, recorded_at desc);

-- ---------------------------------------------------------------------------
-- Current health for each member module
-- ---------------------------------------------------------------------------

create table if not exists public.module_status (
  module_id smallint primary key check (module_id between 1 and 4),
  module_name text not null,
  health_status text not null default 'OFFLINE'
    check (health_status in ('HEALTHY', 'WARNING', 'FAULT', 'OFFLINE')),
  error_code text,
  message text,
  last_seen timestamptz,
  updated_at timestamptz not null default now()
);

drop trigger if exists set_module_status_updated_at on public.module_status;
create trigger set_module_status_updated_at
before update on public.module_status
for each row execute function public.set_updated_at();

insert into public.module_status (module_id, module_name)
values
  (1, 'Irrigation'),
  (2, 'Environment Monitoring'),
  (3, 'Water Tank and Resource Management'),
  (4, 'Crop Health and Visual Monitoring')
on conflict (module_id) do update set module_name = excluded.module_name;

-- ---------------------------------------------------------------------------
-- Commands and actuator results for AUTO/MANUAL evidence
-- ---------------------------------------------------------------------------

create table if not exists public.actuator_events (
  id bigint generated by default as identity primary key,
  module_id smallint not null check (module_id between 1 and 4),
  actuator text not null
    check (actuator in ('PUMP', 'FAN', 'GROW_LED', 'RGB_LED', 'BUZZER')),
  requested_action text not null check (requested_action in ('ON', 'OFF')),
  actual_state text check (actual_state in ('ON', 'OFF', 'UNKNOWN')),
  control_mode text not null check (control_mode in ('AUTO', 'MANUAL')),
  command_source text not null default 'SYSTEM'
    check (command_source in ('SYSTEM', 'DASHBOARD', 'LOCAL', 'SAFETY_LOCK')),
  rule_id text,
  result text not null default 'ACCEPTED'
    check (result in ('ACCEPTED', 'REJECTED', 'FAILED')),
  reason text,
  duration_seconds integer
    check (duration_seconds is null or duration_seconds >= 0),
  created_at timestamptz not null default now()
);

-- Refresh the actuator constraint when upgrading an existing prototype database.
alter table public.actuator_events
  drop constraint if exists actuator_events_actuator_check;
alter table public.actuator_events
  add constraint actuator_events_actuator_check
  check (actuator in ('PUMP', 'FAN', 'GROW_LED', 'RGB_LED', 'BUZZER'));

create index if not exists actuator_events_created_at_idx
  on public.actuator_events (created_at desc);
create index if not exists actuator_events_module_time_idx
  on public.actuator_events (module_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Alerts and acknowledgement history
-- ---------------------------------------------------------------------------

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  module_id smallint check (module_id between 1 and 4),
  alert_type text not null,
  severity text not null check (severity in ('INFO', 'WARNING', 'CRITICAL')),
  message text not null,
  acknowledged boolean not null default false,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  check (
    (acknowledged = false and acknowledged_at is null)
    or acknowledged = true
  )
);

create index if not exists alerts_created_at_idx
  on public.alerts (created_at desc);
create index if not exists alerts_open_idx
  on public.alerts (acknowledged, created_at desc);

-- ---------------------------------------------------------------------------
-- Module 4 image analysis and growth diary
-- HSV supports colour/yellowing evidence.
-- ---------------------------------------------------------------------------

create table if not exists public.crop_health_records (
  id bigint generated by default as identity primary key,
  image_path text not null,
  green_percent numeric(5,2)
    check (green_percent is null or green_percent between 0 and 100),
  yellowing_percent numeric(5,2)
    check (yellowing_percent is null or yellowing_percent between 0 and 100),
  brightness_score numeric(10,2),
  blur_score numeric(10,2),
  temperature_c numeric(5,2)
    check (temperature_c is null or temperature_c between -40 and 85),
  humidity_percent numeric(5,2)
    check (humidity_percent is null or humidity_percent between 0 and 100),
  risk_score numeric(5,2)
    check (risk_score is null or risk_score between 0 and 100),
  risk_level text not null default 'GREEN'
    check (risk_level in ('GREEN', 'AMBER', 'RED')),
  camera_status text not null default 'HEALTHY'
    check (camera_status in ('HEALTHY', 'INVALID_IMAGE', 'OFFLINE', 'FAULT')),
  analysis_status text not null default 'VALID'
    check (analysis_status in ('VALID', 'INVALID', 'ERROR')),
  alert_message text,
  metadata jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Remove the experimental stress/wilting column without deleting rows.
alter table public.crop_health_records
  drop column if exists stress_percent;

create index if not exists crop_health_captured_at_idx
  on public.crop_health_records (captured_at desc);
create unique index if not exists crop_health_image_path_uidx
  on public.crop_health_records (image_path);
create index if not exists crop_health_risk_time_idx
  on public.crop_health_records (risk_level, captured_at desc);

-- ---------------------------------------------------------------------------
-- Private image bucket for Module 4
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'crop-images',
  'crop-images',
  false,
  6291456,
  array['image/jpeg', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- ---------------------------------------------------------------------------
-- RLS and minimum prototype permissions
--
-- The GitHub Pages dashboard uses a public publishable key. These policies
-- intentionally allow SELECT and INSERT, but never DELETE. This is suitable
-- only for non-sensitive assignment prototype data. Move writes to an
-- authenticated backend before any real deployment.
-- ---------------------------------------------------------------------------

alter table public.sensor_data enable row level security;
alter table public.module_status enable row level security;
alter table public.actuator_events enable row level security;
alter table public.alerts enable row level security;
alter table public.crop_health_records enable row level security;

grant usage on schema public to anon, authenticated;

grant select, insert on public.sensor_data to anon, authenticated;
grant select, insert, update on public.module_status to anon, authenticated;
grant select, insert on public.actuator_events to anon, authenticated;
grant select, insert, update on public.alerts to anon, authenticated;
grant select, insert on public.crop_health_records to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists sensor_data_public_read on public.sensor_data;
create policy sensor_data_public_read
on public.sensor_data for select
to anon, authenticated
using (true);

drop policy if exists sensor_data_prototype_insert on public.sensor_data;
create policy sensor_data_prototype_insert
on public.sensor_data for insert
to anon, authenticated
with check (true);

drop policy if exists module_status_public_read on public.module_status;
create policy module_status_public_read
on public.module_status for select
to anon, authenticated
using (true);

drop policy if exists module_status_prototype_insert on public.module_status;
create policy module_status_prototype_insert
on public.module_status for insert
to anon, authenticated
with check (module_id between 1 and 4);

drop policy if exists module_status_prototype_update on public.module_status;
create policy module_status_prototype_update
on public.module_status for update
to anon, authenticated
using (module_id between 1 and 4)
with check (module_id between 1 and 4);

drop policy if exists actuator_events_public_read on public.actuator_events;
create policy actuator_events_public_read
on public.actuator_events for select
to anon, authenticated
using (true);

drop policy if exists actuator_events_prototype_insert on public.actuator_events;
create policy actuator_events_prototype_insert
on public.actuator_events for insert
to anon, authenticated
with check (module_id between 1 and 4);

drop policy if exists alerts_public_read on public.alerts;
create policy alerts_public_read
on public.alerts for select
to anon, authenticated
using (true);

drop policy if exists alerts_prototype_insert on public.alerts;
create policy alerts_prototype_insert
on public.alerts for insert
to anon, authenticated
with check (module_id is null or module_id between 1 and 4);

drop policy if exists alerts_prototype_update on public.alerts;
create policy alerts_prototype_update
on public.alerts for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists crop_health_public_read on public.crop_health_records;
create policy crop_health_public_read
on public.crop_health_records for select
to anon, authenticated
using (true);

drop policy if exists crop_health_prototype_insert on public.crop_health_records;
create policy crop_health_prototype_insert
on public.crop_health_records for insert
to anon, authenticated
with check (image_path like 'module4/%');

drop policy if exists crop_images_read on storage.objects;
create policy crop_images_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'crop-images');

drop policy if exists crop_images_prototype_upload on storage.objects;
create policy crop_images_prototype_upload
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'crop-images'
  and name like 'module4/%'
);

commit;

-- ---------------------------------------------------------------------------
-- Verification query: run automatically after setup in the SQL result panel.
-- ---------------------------------------------------------------------------

select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'sensor_data',
    'module_status',
    'actuator_events',
    'alerts',
    'crop_health_records'
  )
order by table_name;
